# syntax=docker/dockerfile:1
FROM ubuntu:latest
WORKDIR /ollama-matrix
RUN apt update && apt install -y python3 python3-full python3-pip git python3-yaml python3-daemon libolm-dev
# This is temporary workaround to have a fast working version, will have to refactor with a venv
RUN rm -rf /usr/lib/python3.12/EXTERNALLY-MANAGED
#python3 && rm -rf /var/lib/apt/lists/*
RUN pip install matrix-nio[e2e] ollama
COPY . .
CMD python3 /ollama-matrix/__main__.py